apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.29.4
        name: nginx
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      volumes:
      - configMap:
          name: kargo-demo-content
        name: content
